version: '3.7'
services:
    shinyapptest:
      build: ./shiny
      container_name: testshiny
      image: testshiny
      restart: unless-stopped
      networks:
            - backend
      ports:
          - 80:3838
    dockerizedapi:
      build: ./plumber
      container_name: dockerizedapi
      image: dockerizedapi
      restart: unless-stopped
      networks:
            - backend
networks:
  backend:
    external:
      name: backend
     
      

